/*
|--------------------------------------------|
         ⚡️ Generated by Agentsmith ⚡️
      ⚠️ Do not edit this file directly ⚠️
|--------------------------------------------|
*/
export type PromptVariables__hello_world__3_0_0 = {
  name: string;
};
export type PromptVariables__hello_world__2_0_0 = {
  name: string;
};
export type PromptVariables__hello_world__1_0_0 = {
  name: string;
};
export type PromptVariables__luffy__0_0_2 = {
  thread: any;
};
export type PromptVariables__luffy__0_0_1 = {
  thread: any;
};
export type PromptVariables__nami__0_0_1 = {
  thread: any;
};
export type PromptVariables__one_piece_character_response_decision__0_0_4 = {
  characters: any;
  thread: any;
  turnsWithoutResponses?: number;
};
export type PromptVariables__one_piece_character_response_decision__0_0_3 = {
  characters: any;
  thread: any;
  turnsWithoutResponses: number;
};
export type PromptVariables__one_piece_character_response_decision__0_0_2 = {
  characters: any;
  thread: any;
  turnsWithoutResponses: number;
};
export type PromptVariables__one_piece_character_response_decision__0_0_1 = {
  name: string;
  thread: any;
};
export type PromptVariables__prompt_a__0_0_1 = never;
export type PromptConfig__hello_world__3_0_0 = {
  models: ['openrouter/auto'];
  temperature: number;
};
export type PromptVersion__hello_world__3_0_0 = {
  version: '3.0.0';
  config: PromptConfig__hello_world__3_0_0;
  variables: PromptVariables__hello_world__3_0_0;
  content: string;
};
export type PromptConfig__hello_world__2_0_0 = {
  models: ['openrouter/auto'];
  temperature: number;
};
export type PromptVersion__hello_world__2_0_0 = {
  version: '2.0.0';
  config: PromptConfig__hello_world__2_0_0;
  variables: PromptVariables__hello_world__2_0_0;
  content: string;
};
export type PromptConfig__hello_world__1_0_0 = {
  models: ['openrouter/auto'];
  temperature: number;
};
export type PromptVersion__hello_world__1_0_0 = {
  version: '1.0.0';
  config: PromptConfig__hello_world__1_0_0;
  variables: PromptVariables__hello_world__1_0_0;
  content: string;
};
export type Prompt__hello_world = {
  name: 'Hello World';
  slug: 'hello-world';
  versions: {
    latest: never;
    '3.0.0': PromptVersion__hello_world__3_0_0;
    '2.0.0': PromptVersion__hello_world__2_0_0;
    '1.0.0': PromptVersion__hello_world__1_0_0;
  };
};
export type PromptConfig__luffy__0_0_2 = {
  models: ['openrouter/auto'];
  temperature: number;
};
export type PromptVersion__luffy__0_0_2 = {
  version: '0.0.2';
  config: PromptConfig__luffy__0_0_2;
  variables: PromptVariables__luffy__0_0_2;
  content: string;
};
export type PromptConfig__luffy__0_0_1 = {
  models: ['openrouter/auto'];
  temperature: number;
};
export type PromptVersion__luffy__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__luffy__0_0_1;
  variables: PromptVariables__luffy__0_0_1;
  content: string;
};
export type Prompt__luffy = {
  name: 'Luffy';
  slug: 'luffy';
  versions: {
    latest: never;
    '0.0.2': PromptVersion__luffy__0_0_2;
    '0.0.1': PromptVersion__luffy__0_0_1;
  };
};
export type PromptConfig__nami__0_0_1 = {
  models: ['openrouter/auto'];
  temperature: number;
};
export type PromptVersion__nami__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__nami__0_0_1;
  variables: PromptVariables__nami__0_0_1;
  content: string;
};
export type Prompt__nami = {
  name: 'Nami';
  slug: 'nami';
  versions: {
    latest: never;
    '0.0.1': PromptVersion__nami__0_0_1;
  };
};
export type PromptConfig__one_piece_character_response_decision__0_0_4 = {
  models: ['google/gemini-2.5-flash-lite-preview-06-17'];
  temperature: number;
  response_format: {
    type: 'json_schema';
    json_schema: {
      name: 'op_response_reasons';
      schema: {
        type: 'array';
        items: {
          type: 'object';
          required: ['character', 'reasons_to_respond', 'reasons_not_to_respond', 'score'];
          properties: {
            score: {
              type: 'number';
              description: 'score out of 10 determining how likely it would be that the character responds, 10 being most likely and 1 being least likely';
            };
            character: {
              type: 'string';
            };
            reasons_to_respond: {
              type: 'array';
              items: {
                type: 'string';
              };
              description: 'list of reasons why the character would respond to the thread';
            };
            reasons_not_to_respond: {
              type: 'array';
              items: {
                type: 'string';
              };
              description: 'list of reasons why the character would NOT respond to the thread';
            };
          };
          additionalProperties: false;
        };
      };
      strict: true;
    };
  };
};
export type PromptVersion__one_piece_character_response_decision__0_0_4 = {
  version: '0.0.4';
  config: PromptConfig__one_piece_character_response_decision__0_0_4;
  variables: PromptVariables__one_piece_character_response_decision__0_0_4;
  content: string;
};
export type PromptConfig__one_piece_character_response_decision__0_0_3 = {
  models: ['google/gemini-2.5-flash-lite-preview-06-17'];
  temperature: number;
  response_format: {
    type: 'json_schema';
    json_schema: {
      name: 'op_response_reasons';
      schema: {
        type: 'array';
        items: {
          type: 'object';
          required: ['character', 'reasons_to_respond', 'reasons_not_to_respond', 'score'];
          properties: {
            score: {
              type: 'number';
              description: 'score out of 10 determining how likely it would be that the character responds, 10 being most likely and 1 being least likely';
            };
            character: {
              type: 'string';
            };
            reasons_to_respond: {
              type: 'array';
              items: {
                type: 'string';
              };
              description: 'list of reasons why the character would respond to the thread';
            };
            reasons_not_to_respond: {
              type: 'array';
              items: {
                type: 'string';
              };
              description: 'list of reasons why the character would NOT respond to the thread';
            };
          };
          additionalProperties: false;
        };
      };
      strict: true;
    };
  };
};
export type PromptVersion__one_piece_character_response_decision__0_0_3 = {
  version: '0.0.3';
  config: PromptConfig__one_piece_character_response_decision__0_0_3;
  variables: PromptVariables__one_piece_character_response_decision__0_0_3;
  content: string;
};
export type PromptConfig__one_piece_character_response_decision__0_0_2 = {
  models: ['google/gemini-2.5-flash-lite-preview-06-17'];
  temperature: number;
  response_format: {
    type: 'json_schema';
    json_schema: {
      name: 'op_response_reasons';
      schema: {
        type: 'array';
        items: {
          type: 'object';
          required: ['character', 'reasons_to_respond', 'reasons_not_to_respond', 'score'];
          properties: {
            score: {
              type: 'number';
              description: 'score out of 10 determining how likely it would be that the character responds, 10 being most likely and 1 being least likely';
            };
            character: {
              type: 'string';
            };
            reasons_to_respond: {
              type: 'array';
              items: {
                type: 'string';
              };
              description: 'list of reasons why the character would respond to the thread';
            };
            reasons_not_to_respond: {
              type: 'array';
              items: {
                type: 'string';
              };
              description: 'list of reasons why the character would NOT respond to the thread';
            };
          };
          additionalProperties: false;
        };
      };
      strict: true;
    };
  };
};
export type PromptVersion__one_piece_character_response_decision__0_0_2 = {
  version: '0.0.2';
  config: PromptConfig__one_piece_character_response_decision__0_0_2;
  variables: PromptVariables__one_piece_character_response_decision__0_0_2;
  content: string;
};
export type PromptConfig__one_piece_character_response_decision__0_0_1 = {
  models: ['google/gemini-2.5-flash-preview-05-20'];
  temperature: number;
  response_format: {
    type: 'json_schema';
    json_schema: {
      name: 'op_response_reason';
      schema: {
        type: 'object';
        required: ['reasons_to_respond', 'reasons_not_to_respond', 'score'];
        properties: {
          score: {
            type: 'number';
            description: 'score out of 10 determining how likely it would be that the character responds, 10 being most likely and 1 being least likely';
          };
          reasons_to_respond: {
            type: 'array';
            items: {
              type: 'string';
            };
            description: 'list of reasons why the character would respond to the thread';
          };
          reasons_not_to_respond: {
            type: 'array';
            items: {
              type: 'string';
            };
            description: 'list of reasons why the character would NOT respond to the thread';
          };
        };
        additionalProperties: false;
      };
      strict: true;
    };
  };
};
export type PromptVersion__one_piece_character_response_decision__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__one_piece_character_response_decision__0_0_1;
  variables: PromptVariables__one_piece_character_response_decision__0_0_1;
  content: string;
};
export type Prompt__one_piece_character_response_decision = {
  name: 'One Piece Character Response Decision';
  slug: 'one-piece-character-response-decision';
  versions: {
    latest: never;
    '0.0.4': PromptVersion__one_piece_character_response_decision__0_0_4;
    '0.0.3': PromptVersion__one_piece_character_response_decision__0_0_3;
    '0.0.2': PromptVersion__one_piece_character_response_decision__0_0_2;
    '0.0.1': PromptVersion__one_piece_character_response_decision__0_0_1;
  };
};
export type PromptConfig__prompt_a__0_0_1 = {
  models: ['openrouter/auto'];
  temperature: number;
};
export type PromptVersion__prompt_a__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__prompt_a__0_0_1;
  variables: PromptVariables__prompt_a__0_0_1;
  content: string;
};
export type Prompt__prompt_a = {
  name: 'prompt A';
  slug: 'prompt-a';
  versions: {
    latest: never;
    '0.0.1': PromptVersion__prompt_a__0_0_1;
  };
};
export type Globals = {};
export type Agency = {
  prompts: {
    'hello-world': Prompt__hello_world;
    luffy: Prompt__luffy;
    nami: Prompt__nami;
    'one-piece-character-response-decision': Prompt__one_piece_character_response_decision;
    'prompt-a': Prompt__prompt_a;
  };
  globals: Globals;
};
